### ISSUE TITLE
Script For Dataset Generation

### ISSUE THREAD

**Issue by muhammadabdullah34907** [seth814/Mind-Gut-Connection#4]
Hi @seth814 

Hope you are doing well. Sorry for creating issue related to different project. Please I need your small help. (https://github.com/pengzhou1108/RGB-N/issues/12)

I am working on image manipulation detection, I have successfully trained and fine tuned on coco, cover and casia datasets. But for columbia masks are multi-color and not binary mask. So I saw your issue created on original repository, in which you have mentioned that you created the dataset using masks.

So my question is how did you handle the multi-color boundaries to generate the bounding boxes. 

If possible could you share the snippet you used to generate bounding boxes for columbia dataset. 

Looking forward to hear from you.

Thank You.

**Comment by seth814** [comment]
Please don't raise issues in totally unrelated repositories. I have no idea where that code is at this point. But the usual way to do something like that would be to get the color value present for red, green, or blue. Then use https://docs.scipy.org/doc/numpy/reference/generated/numpy.where.html to get the index where these values are present. This essentially gives a mask for each color. You can create bounding boxes from the indices.

I will delete this in a week since it has nothing to do with this repo. You're lucky I even answered your question.

**Comment by muhammadabdullah34907** [comment]
@seth814 
Thank you for replying. Please you can delete this issue now as well. I got your point and I will do this to generate myself. 

peace
